[files]
extend-exclude = [".git", "minq"]
ignore-hidden = false

[default]
check-filename = true
check-file = true
binary = false
locale = "en"
unicode = true

[default.extend-words]
Nd = "Nd"
gam = "gam"
ontext = "ontext"
