name: Check Code Standard Adherence
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  linter_name:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: psf/black@stable
        with:
          options: "--check --diff --config=.black"
          src: "."
