# ----- IBCDFO FULL TESTING OF LOCAL CLONE WITHOUT COVERAGE
name: Test IBCDFO MATLAB Code
env:
  BENDFO_M_PATH:    ${{ github.workspace }}/BenDFO/m
  BENDFO_DATA_PATH: ${{ github.workspace }}/BenDFO/data
  POUNDERS_PATH:    ${{ github.workspace }}/IBCDFO/pounders/m
  MSAMP_PATH:       ${{ github.workspace }}/IBCDFO/manifold_sampling/m
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  test_ibcdfo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13, macos-14]
        matlab-release: ["R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a"]
    steps:
    # -- General Setup Steps
    - name: Checkout IBCDFO repository
      uses: actions/checkout@v4
      with:
        path: IBCDFO
        submodules: recursive
    - name: Checkout BenDFO repository
      uses: actions/checkout@v4
      with:
        repository: POptUS/BenDFO
        path: BenDFO
    - name: Set up MATLAB ${{ matrix.matlab-release }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab-release }}
        products: Optimization_Toolbox

    # -- Test Execution Step
    - name: Test POUNDERS
      uses: matlab-actions/run-command@v2
      with:
        command: >
            addpath("${{ env.BENDFO_M_PATH }}"),
            addpath("${{ env.BENDFO_DATA_PATH }}"),
            cd ${{ env.POUNDERS_PATH }},
            results = runtests("IncludeSubfolders", true),
            assertSuccess(results);

    - name: Test Manifold Sampling
      uses: matlab-actions/run-command@v2
      with:
        command: >
            addpath("${{ env.BENDFO_M_PATH }}"),
            addpath("${{ env.BENDFO_DATA_PATH }}"),
            cd ${{ env.MSAMP_PATH }},
            results = runtests("IncludeSubfolders", true),
            assertSuccess(results),
