# TODO: Eventually tests should be run from the root of the repo so that we run
# all MATLAB test suites and combine all coverage results in a single report.
name: Test IBCDFO MATLAB Code
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_ibcdfo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        matlab-release: ["R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a"]
    steps:
    ##-- General Setup Steps
    - name: Checkout IBCDFO repository
      uses: actions/checkout@v4
      with:
        path: IBCDFO
        submodules: recursive
    - name: Checkout BenDFO repository
      uses: actions/checkout@v4
      with:
        repository: POptUS/BenDFO
        path: BenDFO
    - name: Set up MATLAB ${{ matrix.matlab-release }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab-release }}

    ##-- Test Execution Step
    - name: Test POUNDERS/MATLAB
      uses: matlab-actions/run-command@v2
      with:
        command: >
            addpath("BenDFO/data"),
            addpath("BenDFO/m"),
            cd IBCDFO/pounders/m,
            results = runtests("IncludeSubfolders", true),
            assertSuccess(results);
